version: "3"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Kiev
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /home/gunterpi/hosted/qbittorrent/config:/config
      - /home/gunterpi/hosted/qbittorrent/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080
    networks:
      - rpi
    restart: unless-stopped
    labels:
      - "traefik.http.routers.qbitproxy.rule=Host(`qbit.ubuntu`)"
      - "traefik.http.services.qbit.loadbalancer.server.port=8080"


networks:
  rpi:
    external: true