apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: nodered/node-red:3.1.8-16
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1.5Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nodered-data
--- 

apiVersion: v1
kind: Service
metadata:
  name: nodered-service
spec:
  type: ClusterIP
  selector:
    app: nodered
  ports:
  - port: 1880