version: '3'


includes:
  deploy: ./deploy/Taskfile.yaml

tasks:
  update:
    cmds:
      - git fetch && git pull

  deploy-all:
    cmds:
      - |
        task deploy:iot
        task deploy:infra
