version: '3.8'
services:
    reproxy:
        labels:
            - '__alloy_export=true'
        image: ghcr.io/umputun/reproxy:v1.2.2
        restart: unless-stopped
        volumes:
            - './reproxy/config.yaml:/reproxy/config.yaml'
            - './reproxy/certs:/reproxy/certs'
        command: 'reproxy --mgmt.enabled --mgmt.listen=0.0.0.0:9999 --ssl.type=static --ssl.cert=/reproxy/certs/fullchain.pem --ssl.key=/reproxy/certs/privkey.pem --file.enabled --file.name=/reproxy/config.yaml'
        ports:
          # - '80:8080'
          - '443:8443'
        expose:
          - '8443'
          - '9999' 
        networks:
          - infra
          - iot
          - apps
        environment:
          - HEADER=
            Strict-Transport-Security:max-age=63072000; includeSubDomains
networks:
  iot:
    name: iot
    external: true
  infra:
    name: infra
    external: true
  apps:
    name: apps
    external: true