version: '3.8'
services:
    reproxy:
        image: ghcr.io/umputun/reproxy:v1.2.2
        restart: unless-stopped
        volumes:
            - './reproxy/config.yaml:/reproxy/config.yaml'
        command: 'reproxy --file.enabled --file.name=/reproxy/config.yaml'
        ports:
          - '80:8080'
          - '443:8443'
        networks:
          - infra
          - iot

networks:
  iot:
    name: iot
    external: true
  infra:
    name: infra
    external: true