version: '3.1'

services:
  spendshelfui:
    container_name: spendshelfui
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - rpi
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.http.routers.spendshelfuiproxy.rule=Host(`spendshelf.ubuntu`)"
      - "traefik.http.services.spendshelfui.loadbalancer.server.port=80"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  rpi:
    external: true
