version: "3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - UMASK_SET=022 #optional
      - # add your PLEX_CLAIM=CLAIM
    volumes:
      - /home/gunterpi/hosted/plex/config:/config
      - /home/gunterpi/hosted/qbittorrent/downloads/tv:/tv
      - /home/gunterpi/hosted/qbittorrent/downloads/movies:/movies
    restart: unless-stopped

networks:
  rpi:
    external: true
