version: 4

homeassistant:
    enabled: false

frontend:
    enabled: true
    port: 8080

mqtt:
    base_topic: zigbee2mqtt
    server: 'mqtt://mqtt'
    user: my_user
    password: my_password

serial:
    port: /dev/ttyACM0
    adapter: ember

availability:
    enabled: true

advanced:
    last_seen: epoch
    elapsed: true
    network_key: GENERATE
    pan_id: GENERATE
    ext_pan_id: GENERATE
