version: "3"
services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.dashboard --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rpi
    restart: unless-stopped
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.ubuntu`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      # add your password + username
      # see https://docs.traefik.io/middlewares/basicauth/
      # - "traefik.http.middlewares.auth.basicauth.users=USERNAME:HASHED PASSWORD"
networks:
  rpi:
    external: true