services:

  dash:
    image: ghcr.io/suddengunter/hsd:v0.3.1
    restart: unless-stopped
    env_file: hsd.env 
    expose:
      - 8080/tcp
    networks:
      - apps

networks:
  apps:
    name: apps
    external: true
