services:

  dash:
    image: ghcr.io/suddengunter/hsd:v0.3.4
    restart: unless-stopped
    env_file: hsd.env 
    expose:
      - 8080/tcp
    networks:
      - apps
      - iot

networks:
  apps:
    name: apps
    external: true
  iot:
    name: iot
    external: true
