version: '3'

tasks:
  iot:
    cmds:
      - task: compose
        vars:
          NETWORK: 'iot'
          APP: 'mqtt'
  infra:
    cmds:
      - task: compose
        vars:
          NETWORK: 'infra'
          APP: 'reproxy'
  compose:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        echo "Deploying $APP on $NETWORK network"
        if ! docker network ls | grep -q "$NETWORK"; then
          echo "Creating Docker network: $NETWORK"
          docker network create "$NETWORK"
        else
          echo "Docker network $NETWORK already exists."
        fi

        docker compose -f $NETWORK/$APP/docker-compose.yaml up -d --remove-orphans --wait
    requires:
      vars: [NETWORK, APP]