version: "3"

services:
  deconz:
    container_name: deconz
    image: marthoc/deconz:aarch64-2.05.77
    ports:
      - "80/tcp"
      - "8443:8443/tcp"
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_VNC_MODE=0
      - DECONZ_WS_PORT=8443
      - TZ=Europe/Kiev
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - '/opt/deconz:/root/.local/share/dresden-elektronik/deCONZ'
    networks:
      - rpi
    restart: unless-stopped
    labels:
      - "traefik.http.routers.deconzproxy.rule=Host(`deconz.ubuntu`)"
      - "traefik.http.services.deconz.loadbalancer.server.port=80"
networks:
  rpi:
     external: true