version: '3.8'
services:
    mqtt:
        image: eclipse-mosquitto:2.0
        restart: unless-stopped
        volumes:
            - './mqtt/mosquitto-data:/mosquitto'
            - './mqtt/custom.conf:/mqttconf/custom.conf'
            - './mqtt/mqttcreds.txt:/mqttconf/mqttcreds.txt'
        command: 'mosquitto -c /mqttconf/custom.conf'
        expose:
          - 1883/tcp
        networks:
          - iot
    zigbee2mqtt:
        restart: unless-stopped
        image: koenkk/zigbee2mqtt:1.39.1
        volumes:
            - ./zigbee2mqtt:/app/data
            - /run/udev:/run/udev:ro
        environment:
            - TZ=Europe/London
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        expose:
            - 8080/tcp
        networks:
          - iot
    mqtt-exporter:
      labels:
          - '__alloy_export=true'
      restart: unless-stopped
      image: kpetrem/mqtt-exporter:1.4.7
      ports:
          - 9000:9000
      environment:
          - MQTT_ADDRESS=mqtt
          - MQTT_ADDRESS=/run/secrets/mqttname
          - MQTT_PASSWORD=/run/secrets/mqttpassword
          - PROMETHEUS_PORT=9999
      expose:
        - 9999/tcp
      networks:
        - iot

networks:
  iot:
    name: iot
    external: true

secrets:
   mqttname:
     file: mqttname.txt # plaintext file  with mqtt user name
   mqttpassword:
     file: mqttpassword.txt # plaintext file with mqtt password
