version: '3.8'
services:
    mqtt:
        image: eclipse-mosquitto:2.0
        restart: unless-stopped
        volumes:
            - './mqtt/mosquitto-data:/mosquitto'
            - './mqtt/custom.conf:/mqttconf/custom.conf'
            - './mqtt/mqttcreds.txt:/mqttconf/mqttcreds.txt'
        command: 'mosquitto -c /mqttconf/custom.conf'
        expose:
          - 1883/tcp
        networks:
          - iot
    zigbee2mqtt:
        restart: unless-stopped
        image: koenkk/zigbee2mqtt:1.39.1
        volumes:
            - ./zigbee2mqtt:/app/data
            - /run/udev:/run/udev:ro
        environment:
            - TZ=Europe/London
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        expose:
          - 8080/tcp
        networks:
          - iot

networks:
  iot:
    name: iot
    external: true